### ISSUE TITLE
[Bug] Kodi crashes when using version 2.0.0 or higher

### ISSUE THREAD

**Issue by matke-84** [MikeSiLVO/script.skinshortcuts#102]
I have been using version 1.1.5 for a long time because since version 2.0.0 I have a problem with Kodi crashing when using addons that use arrow. Yes I know, the answer will probably be, what does it have to do with skin shortcuts. But this happens at the moment I install the latest version 2.0.3 or any version since 2.0.0. The message is always the same and the Kodi crash happens. When I use version 1.1.5 everything is perfectly fine.  What is this about? What is so different about version 2.0.0 when this happens?
```
2023-06-26 22:53:35.484 T:8380    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'datetime.timedelta' object has no attribute 'timestamp'
                                                   Traceback (most recent call last):
                                                     File "C:\Users\Marko\AppData\Roaming\Kodi\addons\script.embuary.info\default.py", line 7, in <module>
                                                       from resources.lib.helper import *
                                                     File "C:\Users\Marko\AppData\Roaming\Kodi\addons\script.embuary.info\resources\lib\helper.py", line 15, in <module>
                                                       import arrow
                                                     File "C:\Users\Marko\AppData\Roaming\Kodi\addons\script.module.arrow\lib\arrow\__init__.py", line 2, in <module>
                                                       from .api import get, now, utcnow
                                                     File "C:\Users\Marko\AppData\Roaming\Kodi\addons\script.module.arrow\lib\arrow\api.py", line 12, in <module>
                                                       from arrow.arrow import TZ_EXPR, Arrow
                                                     File "C:\Users\Marko\AppData\Roaming\Kodi\addons\script.module.arrow\lib\arrow\arrow.py", line 34, in <module>
                                                       from arrow import formatter, locales, parser, util
                                                     File "C:\Users\Marko\AppData\Roaming\Kodi\addons\script.module.arrow\lib\arrow\parser.py", line 26, in <module>
                                                       from arrow.util import next_weekday, normalize_timestamp
                                                     File "C:\Users\Marko\AppData\Roaming\Kodi\addons\script.module.arrow\lib\arrow\util.py", line 6, in <module>
                                                       from arrow.constants import (
                                                     File "C:\Users\Marko\AppData\Roaming\Kodi\addons\script.module.arrow\lib\arrow\constants.py", line 16, in <module>
                                                       _MAX_TIMESTAMP = datetime.max.timestamp()
                                                   AttributeError: 'datetime.timedelta' object has no attribute 'timestamp'
                                                   -->End of Python script error report<--

```
```
2023-06-26 22:53:34.860 T:7540    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'datetime.timedelta' object has no attribute 'timestamp'
                                                   Traceback (most recent call last):
                                                     File "C:\Users\Marko\AppData\Roaming\Kodi\addons\script.skin.helper.widgets\plugin.py", line 9, in <module>
                                                       import main
                                                     File "C:\Users\Marko\AppData\Roaming\Kodi\addons\script.skin.helper.widgets\resources\lib\main.py", line 17, in <module>
                                                       from metadatautils import MetadataUtils
                                                     File "C:\Users\Marko\AppData\Roaming\Kodi\addons\script.module.metadatautils\lib\metadatautils.py", line 10, in <module>
                                                       import helpers.kodi_constants as kodi_constants
                                                     File "C:\Users\Marko\AppData\Roaming\Kodi\addons\script.module.metadatautils\lib\helpers\kodi_constants.py", line 10, in <module>
                                                       from .utils import KODI_VERSION
                                                     File "C:\Users\Marko\AppData\Roaming\Kodi\addons\script.module.metadatautils\lib\helpers\utils.py", line 13, in <module>
                                                       import arrow
                                                     File "C:\Users\Marko\AppData\Roaming\Kodi\addons\script.module.arrow\lib\arrow\__init__.py", line 2, in <module>
                                                       from .api import get, now, utcnow
                                                     File "C:\Users\Marko\AppData\Roaming\Kodi\addons\script.module.arrow\lib\arrow\api.py", line 12, in <module>
                                                       from arrow.arrow import TZ_EXPR, Arrow
                                                     File "C:\Users\Marko\AppData\Roaming\Kodi\addons\script.module.arrow\lib\arrow\arrow.py", line 34, in <module>
                                                       from arrow import formatter, locales, parser, util
                                                     File "C:\Users\Marko\AppData\Roaming\Kodi\addons\script.module.arrow\lib\arrow\parser.py", line 26, in <module>
                                                       from arrow.util import next_weekday, normalize_timestamp
                                                     File "C:\Users\Marko\AppData\Roaming\Kodi\addons\script.module.arrow\lib\arrow\util.py", line 6, in <module>
                                                       from arrow.constants import (
                                                     File "C:\Users\Marko\AppData\Roaming\Kodi\addons\script.module.arrow\lib\arrow\constants.py", line 16, in <module>
                                                       _MAX_TIMESTAMP = datetime.max.timestamp()
                                                   AttributeError: 'datetime.timedelta' object has no attribute 'timestamp'
                                                   -->End of Python script error report<--
```

**Comment by MikeSiLVO** [comment]
The error shows an issue with arrow's datetime. Something else caused that.
skinshortcuts doesn't use datetime at all.

I assume its a coincidence when skinshortcuts loads because other addons (embuary.info, skin.helper.widgets) get triggered around the same time and they import arrow.
