### ISSUE TITLE
Skinshortcuts error

### ISSUE THREAD

**Issue by matke-84** [MikeSiLVO/script.skinshortcuts#103]
I often get this error when kodi loading. Skinshortcuts 2.0.3.

```
2023-07-13 14:24:05.878 T:20208   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'xml.etree.ElementTree.ParseError'>
                                                   Error Contents: no element found: line 1, column 0
                                                   Traceback (most recent call last):
                                                     File "C:\Users\marko\AppData\Roaming\Kodi\addons\script.skinshortcuts\resources\lib\entry_point.py", line 16, in <module>
                                                       script.route()
                                                     File "C:\Users\marko\AppData\Roaming\Kodi\addons\script.skinshortcuts\resources\lib\skinshorcuts\skinshortcuts.py", line 78, in route
                                                       route_method()
                                                     File "C:\Users\marko\AppData\Roaming\Kodi\addons\script.skinshortcuts\resources\lib\skinshorcuts\skinshortcuts.py", line 83, in route_buildxml
                                                       self.xml_func.build_menu(self.MENUID, self.GROUP, self.LEVELS,
                                                     File "C:\Users\marko\AppData\Roaming\Kodi\addons\script.skinshortcuts\resources\lib\skinshorcuts\xmlfunctions.py", line 71, in build_menu
                                                       tree = ETree.fromstring(contents)
                                                     File "C:\Program Files\Kodi\system\python\Lib\xml\etree\ElementTree.py", line 1321, in XML
                                                       return parser.close()
                                                   xml.etree.ElementTree.ParseError: no element found: line 1, column 0
                                                   -->End of Python script error report<--

```

**Comment by MikeSiLVO** [comment]
Added ParseError alongside FileNotFoundError when parsing XML for more informative xml issues.
Hopefully that will help narrow down what the issue is in the future.
